# -*- coding: utf-8 -*-
"""Untitled42.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AzSYbK0-Nk0Q7f4IE4OWNiSWVIHqo4Nn
"""

import requests
import pandas as pd
import numpy as np
import nest_asyncio
import asyncio
import re
from datetime import datetime, timedelta, time, date as dt_date
from telethon import TelegramClient, types
from telethon.errors import SessionPasswordNeededError
import os
from pytz import timezone as pytz_timezone
from transformers import AutoTokenizer, AutoModelForSequenceClassification, pipeline
import torch
import joblib
from tensorflow.keras.models import load_model
from sklearn.preprocessing import MinMaxScaler
import praw
import sqlite3
import math

from flask import Flask, request, jsonify
from flask_cors import CORS
import traceback
import threading

from flask_sqlalchemy import SQLAlchemy
from sqlalchemy import desc, event, func
from sqlalchemy.engine import Engine
from apscheduler.schedulers.background import BackgroundScheduler
from sqlalchemy.exc import IntegrityError
import atexit
from flask_migrate import Migrate

nest_asyncio.apply()

app = Flask(__name__)
CORS(app)

app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///bitcoin_features.db'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
db = SQLAlchemy(app)
migrate = Migrate(app, db)

telethon_session_lock = threading.Lock()

def replace_nan_with_none(data):
    if isinstance(data, dict):
        return {k: replace_nan_with_none(v) for k, v in data.items()}
    elif isinstance(data, list):
        return [replace_nan_with_none(i) for i in data]
    elif isinstance(data, float):
        if math.isnan(data):
            return None
    elif hasattr(np, 'floating') and isinstance(data, np.floating):
        if np.isnan(data):
            return None
    return data

@event.listens_for(Engine, "connect")
def set_sqlite_pragma(dbapi_connection, connection_record):
    cursor = dbapi_connection.cursor()
    try:
        cursor.execute("PRAGMA journal_mode=WAL;")
        cursor.execute("PRAGMA busy_timeout = 10000;")
    except Exception as e:
        print(f"Error setting PRAGMA for main DB: {e}")
    finally:
        cursor.close()

TELEGRAM_API_ID = os.environ.get("TELEGRAM_API_ID", "21764785")
TELEGRAM_API_HASH = os.environ.get("TELEGRAM_API_HASH", "a502c9bdf77efd81ad2bb0e3c9c1f8c1")
TELEGRAM_PHONE = os.environ.get("TELEGRAM_PHONE", "+962787341582")
TELEGRAM_GROUPS_CONFIG = ["@BITCOINNEWS"]
MESSAGE_LOOKBACK_DAYS = 30
MAX_MESSAGES_PER_FETCH_FOR_RATIOS = 1000
MAX_MESSAGES_TO_STORE_PER_GROUP = 200
MAX_REDDIT_ITEMS_TO_STORE = 150

MODEL_PATH = "bitcoin_full_data_model_5day.keras"
SCALER_PATH = "bitcoin_scaler.save"

REDDIT_CLIENT_ID = os.environ.get("REDDIT_CLIENT_ID", "b-jBdyOdvyF_QtuCGAcmDQ")
REDDIT_CLIENT_SECRET = os.environ.get("REDDIT_CLIENT_SECRET", "rJbCy6rSzQfygFGzKdVpcb5C4Nbt1Q")
REDDIT_USER_AGENT = os.environ.get("REDDIT_USER_AGENT", "script:bitcoin_post_fetcher:v1.0 (by /u/Hot-Relationship8726)")

SEQUENCE_LENGTH = 50
PREDICTION_HORIZON = 5
HOLD_THRESHOLD_USD = 500

features = [
    'close', 'high', 'low', 'open', 'volume',
    'positive_ratio', 'negative_ratio', 'neutral_ratio',
    'SMA_20', 'EMA_20', 'RSI', 'Bollinger_Upper', 'Bollinger_Lower', 'Volatility',
    'SMA_50', 'SMA_100'
]

_sentiment_pipeline_cache_obj = None
_model_cache = None
_scaler_cache = None

class DailyFeatures(db.Model):
    __tablename__ = 'daily_features'
    id = db.Column(db.Integer, primary_key=True)
    date = db.Column(db.Date, unique=True, nullable=False, index=True)
    for feature_name in features:
        if not feature_name.isidentifier(): raise ValueError(f"Invalid feature name: {feature_name}")
        vars()[feature_name] = db.Column(db.Float, nullable=True)
    prediction = db.relationship('ModelPredictions', foreign_keys='ModelPredictions.prediction_date_fk_val',
                                 backref='daily_feature_for_prediction_date', uselist=False)
    def __repr__(self): return f'<DailyFeatures {self.date}>'

class TelegramMessage(db.Model):
    __tablename__ = 'telegram_messages'
    id = db.Column(db.Integer, primary_key=True)
    telegram_message_id = db.Column(db.Integer, nullable=False)
    chat_id = db.Column(db.BigInteger, nullable=False)
    message_text = db.Column(db.Text, nullable=True)
    message_date = db.Column(db.DateTime, nullable=False, index=True)
    sentiment_label = db.Column(db.String(20), nullable=True)
    source_group = db.Column(db.String(255), nullable=True)
    __table_args__ = (db.UniqueConstraint('telegram_message_id', 'chat_id', name='_telegram_message_chat_uc'),)
    def __repr__(self): return f'<TelegramMessage {self.telegram_message_id} from {self.source_group}>'

class RedditMessage(db.Model):
    __tablename__ = 'reddit_messages'
    id = db.Column(db.Integer, primary_key=True)
    reddit_item_id = db.Column(db.String(20), nullable=False, unique=True, index=True)
    subreddit = db.Column(db.String(255), nullable=False)
    message_text = db.Column(db.Text, nullable=True)
    message_date = db.Column(db.DateTime, nullable=False, index=True)
    sentiment_label = db.Column(db.String(20), nullable=True)
    source_platform = db.Column(db.String(50), nullable=False)
    score = db.Column(db.Integer, nullable=True)
    def __repr__(self): return f'<RedditMessage {self.reddit_item_id} from r/{self.subreddit}>'

class ModelPredictions(db.Model):
    __tablename__ = 'model_predictions'
    id = db.Column(db.Integer, primary_key=True)
    prediction_date_fk_val = db.Column('prediction_date', db.Date, db.ForeignKey('daily_features.date'), nullable=False, index=True)
    base_features_date = db.Column(db.Date, db.ForeignKey('daily_features.date'), nullable=False, index=True)
    predicted_price = db.Column(db.Float, nullable=True)
    signal = db.Column(db.String(10), nullable=True)
    confidence = db.Column(db.Float, nullable=True)
    base_daily_feature = db.relationship('DailyFeatures', foreign_keys=[base_features_date])
    __table_args__ = (db.UniqueConstraint('prediction_date', 'base_features_date', name='_prediction_for_date_from_base_uc'),)
    def __repr__(self):
        return f'<ModelPrediction for {self.prediction_date_fk_val} (price: {self.predicted_price}, signal: {self.signal}) based on {self.base_features_date}>'

def normalize_sentiment_ratios(p, n, u):
    p_val = float(p) if pd.notna(p) else 0.0; n_val = float(n) if pd.notna(n) else 0.0; u_val = float(u) if pd.notna(u) else 0.0
    total = p_val + n_val + u_val
    if total == 0: return 0.0, 0.0, 100.0
    p_norm = (p_val / total) * 100; n_norm = (n_val / total) * 100; u_norm = (u_val / total) * 100
    current_sum = p_norm + n_norm + u_norm
    if abs(current_sum - 100.0) > 0.01:
        diff = 100.0 - current_sum
        if u_norm >= p_norm and u_norm >= n_norm: u_norm += diff
        elif p_norm >= u_norm and p_norm >= n_norm: p_norm += diff
        else: n_norm += diff
    final_sum = p_norm + n_norm + u_norm
    if abs(final_sum - 100.0) > 0.01 :
        p_norm = max(0,p_norm); n_norm = max(0,n_norm); u_norm = max(0,u_norm)
        final_total_check = p_norm + n_norm + u_norm
        if final_total_check > 0 : p_norm = (p_norm / final_total_check) * 100; n_norm = (n_norm / final_total_check) * 100; u_norm = 100 - p_norm - n_norm
        else: p_norm, n_norm, u_norm = 0.0, 0.0, 100.0
    return round(p_norm, 1), round(n_norm, 1), round(u_norm, 1)

def get_btc_data(days=170):
    url = "https://api.coingecko.com/api/v3/coins/bitcoin/market_chart"
    params = { "vs_currency": "usd", "days": str(days), "interval": "daily" }
    try:
        response = requests.get(url, params=params); response.raise_for_status(); data = response.json()
        prices = data["prices"]; volumes = data["total_volumes"]
        df = pd.DataFrame(prices, columns=["timestamp", "close"])
        df["volume"] = [v[1] for v in volumes]; df["date"] = pd.to_datetime(df["timestamp"], unit="ms").dt.normalize()
        df["close"] = df["close"].astype(float); df["volume"] = df["volume"].astype(float)
        try:
            ohlc_url = f"https://api.coingecko.com/api/v3/coins/bitcoin/ohlc"; ohlc_params = {"vs_currency": "usd", "days": str(days)}
            ohlc_response = requests.get(ohlc_url, params=ohlc_params); ohlc_response.raise_for_status(); ohlc_data = ohlc_response.json()
            ohlc_df_raw = pd.DataFrame(ohlc_data, columns=['timestamp', 'open', 'high', 'low', 'close_ohlc'])
            ohlc_df_raw['date'] = pd.to_datetime(ohlc_df_raw['timestamp'], unit='ms').dt.normalize()
            for col in ['open', 'high', 'low', 'close_ohlc']:
                if col in ohlc_df_raw: ohlc_df_raw[col] = pd.to_numeric(ohlc_df_raw[col], errors='coerce')
            ohlc_df_raw = ohlc_df_raw[['date', 'open', 'high', 'low', 'close_ohlc']]
            df = pd.merge(df, ohlc_df_raw, on='date', how='left')
            if 'close_ohlc' in df.columns and not df['close_ohlc'].isnull().all(): df['close'] = df['close_ohlc'].fillna(df['close'])
            df.drop(columns=['close_ohlc'], inplace=True, errors='ignore')
            df["open"] = df["open"].fillna(df["close"].shift(1))
            if "open" not in df.columns or df["open"].isnull().all(): df["open"] = df["close"]
            df["high"] = df["high"].fillna(df[["open", "close"]].max(axis=1))
            df["low"] = df["low"].fillna(df[["open", "close"]].min(axis=1))
        except Exception as ohlc_e:
            print(f"Could not fetch detailed OHLC, using approximations: {ohlc_e}")
            df["open"] = df["close"].shift(1)
            if "open" not in df.columns or df["open"].isnull().all(): df["open"] = df["close"]
            df["high"] = df[["open", "close"]].max(axis=1); df["low"] = df[["open", "close"]].min(axis=1)
        df = df[['date', 'open', 'high', 'low', 'close', 'volume']].ffill().bfill()
        df['SMA_20'] = df['close'].rolling(window=20).mean(); df['SMA_50'] = df['close'].rolling(window=50).mean(); df['SMA_100'] = df['close'].rolling(window=100).mean()
        df['EMA_20'] = df['close'].ewm(span=20, adjust=False).mean()
        delta = df['close'].diff(); gain = delta.where(delta > 0, 0).rolling(window=14).mean(); loss = (-delta.where(delta < 0, 0)).rolling(window=14).mean()
        rs = gain / loss.replace(0, np.nan); df['RSI'] = (100 - (100 / (1 + rs))).fillna(50)
        rolling_mean_bb = df['close'].rolling(window=20).mean(); rolling_std_bb = df['close'].rolling(window=20).std()
        df['Bollinger_Upper'] = rolling_mean_bb + (rolling_std_bb * 2); df['Bollinger_Lower'] = rolling_mean_bb - (rolling_std_bb * 2)
        df['Volatility'] = df['close'].rolling(window=20).std()
        for col in features:
            if col not in df.columns and col not in ['positive_ratio', 'negative_ratio', 'neutral_ratio']: df[col] = 0.0
        df = df.ffill().bfill()
        return df
    except Exception as e: print(f"Error fetching BTC data: {e}"); traceback.print_exc(); return pd.DataFrame()

def clean_message_for_sentiment_analysis(message_text):
    if not message_text or not isinstance(message_text, str): return ""
    text_to_clean = message_text; text_to_clean = re.sub(r'http\S+|www\S+', '', text_to_clean)
    text_to_clean = re.sub(r'\*\*(.*?)\*\*', r'\1', text_to_clean); text_to_clean = re.sub(r'__(.*?)__', r'\1', text_to_clean)
    text_to_clean = re.sub(r'~~(.*?)~~', r'\1', text_to_clean); text_to_clean = re.sub(r'`(.*?)`', r'\1', text_to_clean)
    text_to_clean = re.sub(r'```(.*?)```', r'\1', text_to_clean, flags=re.DOTALL)
    try:
        emoji_pattern = re.compile("[""\U0001F600-\U0001F64F""\U0001F300-\U0001F5FF""\U0001F680-\U0001F6FF""\U0001F700-\U0001F77F"
                                   "\U0001F780-\U0001F7FF""\U0001F800-\U0001F8FF""\U0001F900-\U0001F9FF""\U0001FA00-\U0001FA6F"
                                   "\U0001FA70-\U0001FAFF""\U00002702-\U000027B0""\U000024C2-\U0001F251""\U0001f926-\U0001f937"
                                   "\U00010000-\U0010ffff""]+", flags=re.UNICODE)
        text_to_clean = emoji_pattern.sub(r'', text_to_clean)
    except re.error: text_to_clean = re.sub(r'[\U0001F600-\U0001F64F]+', '', text_to_clean)
    text_to_clean = re.sub(r'#(\w+)', r'\1', text_to_clean); text_to_clean = re.sub(r'@(\w+)', r'\1', text_to_clean)
    text_to_clean = re.sub(r'[^\w\s.,!?\'"$€£%&\-+=]', '', text_to_clean, flags=re.UNICODE)
    text_to_clean = re.sub(r'\s+', ' ', text_to_clean).strip()
    return text_to_clean

def analyze_sentiment(text_for_analysis, sentiment_pipeline):
    try:
        if not text_for_analysis or len(text_for_analysis.strip()) == 0: return 'Neutral'
        result = sentiment_pipeline(text_for_analysis[:512])
        if result and isinstance(result, list) and len(result) > 0 and 'label' in result[0]: return result[0]['label']
        return 'Neutral'
    except Exception as e: print(f"Sentiment analysis error: {e}"); return 'Neutral'

def fetch_reddit_bitcoin_data(start_date, sentiment_pipeline, store_in_db=True):
    items_for_ratios, stored_count, processed_ids = [], 0, set()
    try:
        reddit = praw.Reddit(client_id=REDDIT_CLIENT_ID, client_secret=REDDIT_CLIENT_SECRET, user_agent=REDDIT_USER_AGENT)
        subreddit_name = "Bitcoin"
        fetch_limit_per_category = (MAX_REDDIT_ITEMS_TO_STORE // 3) + 1 if MAX_REDDIT_ITEMS_TO_STORE > 0 else 50
        if fetch_limit_per_category == 0 and MAX_REDDIT_ITEMS_TO_STORE > 0: fetch_limit_per_category = 1
        for method_name, time_filter_val, limit_val in [('top', 'week', fetch_limit_per_category), ('new', None, fetch_limit_per_category), ('hot', None, fetch_limit_per_category)]:
            if store_in_db and stored_count >= MAX_REDDIT_ITEMS_TO_STORE : break
            posts_gen = getattr(reddit.subreddit(subreddit_name), method_name)(limit=limit_val, time_filter=time_filter_val) if method_name == 'top' and time_filter_val else getattr(reddit.subreddit(subreddit_name), method_name)(limit=limit_val)
            for post in posts_gen:
                if post.id in processed_ids: continue
                processed_ids.add(post.id); post_date = datetime.fromtimestamp(post.created_utc, tz=pytz_timezone('UTC')).replace(tzinfo=None)
                if post_date.date() >= start_date.date():
                    original_text = f"{post.title} {post.selftext}"; text_for_sentiment = clean_message_for_sentiment_analysis(original_text); sentiment = analyze_sentiment(text_for_sentiment, sentiment_pipeline)
                    items_for_ratios.append({"date": post_date.isoformat(), "sentiment": sentiment, "source": "reddit_post", "score": post.score, "text_for_sentiment": text_for_sentiment})
                    if store_in_db and stored_count < MAX_REDDIT_ITEMS_TO_STORE and not RedditMessage.query.filter_by(reddit_item_id=post.id).first():
                        db_reddit_msg = RedditMessage(reddit_item_id=post.id, subreddit=subreddit_name, message_text=text_for_sentiment[:2000], message_date=post_date, sentiment_label=sentiment, source_platform='reddit_post', score=post.score)
                        db.session.add(db_reddit_msg)
                        try: db.session.commit(); stored_count += 1
                        except IntegrityError: db.session.rollback()
                        except Exception as e_db: db.session.rollback(); print(f"  DB commit error Reddit post {post.id}: {e_db}")
                    if store_in_db and stored_count >= MAX_REDDIT_ITEMS_TO_STORE: break
                    post.comments.replace_more(limit=0)
                    for comment_idx, comment in enumerate(list(post.comments)[:5]):
                        if comment.id in processed_ids: continue
                        processed_ids.add(comment.id)
                        if hasattr(comment, 'created_utc') and hasattr(comment, 'body'):
                            comment_date = datetime.fromtimestamp(comment.created_utc, tz=pytz_timezone('UTC')).replace(tzinfo=None)
                            if comment_date.date() >= start_date.date():
                                original_comment_text = comment.body; comment_text_for_sentiment = clean_message_for_sentiment_analysis(original_comment_text); comment_sentiment = analyze_sentiment(comment_text_for_sentiment, sentiment_pipeline)
                                items_for_ratios.append({"date": comment_date.isoformat(), "sentiment": comment_sentiment, "source": "reddit_comment", "score": comment.score, "text_for_sentiment": comment_text_for_sentiment})
                                if store_in_db and stored_count < MAX_REDDIT_ITEMS_TO_STORE and not RedditMessage.query.filter_by(reddit_item_id=comment.id).first():
                                    db_reddit_comment = RedditMessage(reddit_item_id=comment.id, subreddit=subreddit_name, message_text=comment_text_for_sentiment[:2000], message_date=comment_date, sentiment_label=comment_sentiment, source_platform='reddit_comment', score=comment.score)
                                    db.session.add(db_reddit_comment)
                                    try: db.session.commit(); stored_count += 1
                                    except IntegrityError: db.session.rollback()
                                    except Exception as e_db_comment: db.session.rollback(); print(f"  DB commit error Reddit comment {comment.id}: {e_db_comment}")
                        if store_in_db and stored_count >= MAX_REDDIT_ITEMS_TO_STORE: break
                if store_in_db and stored_count >= MAX_REDDIT_ITEMS_TO_STORE: break
        return items_for_ratios
    except praw.exceptions.PRAWException as pe: print(f" Reddit API Error: {pe}");
    except Exception as e: print(f"Reddit Fetch/Store Error: {e}");
    return items_for_ratios

async def scrape_telegram_messages(start_date_dt, end_date_dt, group_names, session_path_str, sentiment_pipeline, store_messages_in_db=True):
    if not session_path_str.endswith(".session"): session_path_str = os.path.splitext(os.path.basename(session_path_str))[0]
    client = TelegramClient(session_path_str, TELEGRAM_API_ID, TELEGRAM_API_HASH)
    messages_for_ratios, stored_count = [], 0
    if not telethon_session_lock.acquire(timeout=15): print(f"⚠️ TG Lock Timeout: {session_path_str}. Skipping."); return messages_for_ratios
    try:
        await client.connect()
        if not await client.is_user_authorized():
            print(f"TG session '{session_path_str}' not authorized. Manual input needed.")
            try:
                await client.send_code_request(TELEGRAM_PHONE); code = await asyncio.to_thread(input, f"TG Code for {TELEGRAM_PHONE} ({session_path_str}): ")
                await client.sign_in(TELEGRAM_PHONE, code=code)
            except SessionPasswordNeededError: password = await asyncio.to_thread(input, f"2FA for {TELEGRAM_PHONE} ({session_path_str}): "); await client.sign_in(password=password)
            print(f" TG session '{session_path_str}' authorized!")
        start_target, end_target = start_date_dt.date(), end_date_dt.date()
        for group_username in group_names:
            group_stored_count = 0
            try:
                fetch_limit = MAX_MESSAGES_PER_FETCH_FOR_RATIOS
                raw_cnt, group_processed_cnt = 0, 0
                async for msg in client.iter_messages(group_username, limit=fetch_limit):
                    raw_cnt += 1
                    if not (msg and msg.date and hasattr(msg, 'text') and msg.text and isinstance(msg.chat_id, int)): continue
                    msg_date_naive = msg.date.replace(tzinfo=None); msg_date_compare = msg_date_naive.date()
                    if start_target <= msg_date_compare <= end_target:
                        text_for_sentiment = clean_message_for_sentiment_analysis(msg.text); sentiment = analyze_sentiment(text_for_sentiment, sentiment_pipeline)
                        messages_for_ratios.append({"date": msg_date_naive.isoformat(), "sentiment": sentiment, "source": "telegram"}); group_processed_cnt += 1
                        if store_messages_in_db and group_stored_count < MAX_MESSAGES_TO_STORE_PER_GROUP and not TelegramMessage.query.filter_by(telegram_message_id=msg.id, chat_id=msg.chat_id).first():
                            with app.app_context():
                                db_msg = TelegramMessage(telegram_message_id=msg.id, chat_id=msg.chat_id, message_text=text_for_sentiment[:1000], message_date=msg_date_naive, sentiment_label=sentiment, source_group=group_username)
                                db.session.add(db_msg)
                                try: db.session.commit(); stored_count += 1; group_stored_count += 1
                                except IntegrityError: db.session.rollback()
                                except Exception as e_db: db.session.rollback(); print(f"  DB commit error TG msg {msg.id}: {e_db}")
                    if msg_date_compare < start_target or (store_messages_in_db and group_stored_count >= MAX_MESSAGES_TO_STORE_PER_GROUP and group_processed_cnt > MAX_MESSAGES_TO_STORE_PER_GROUP): break
            except Exception as e_grp: print(f"  Error processing group {group_username}: {e_grp}");
    except sqlite3.OperationalError as e_sql_op:
        if "database is locked" in str(e_sql_op): print(f"SQLite Lock session {session_path_str}: {e_sql_op}")
        else: print(f"SQLite OpError session {session_path_str}: {e_sql_op}")
    except Exception as e_cli: print(f"TG Client Error session {session_path_str}: {e_cli}");
    finally:
        if client.is_connected():
            try: await client.disconnect();
            except Exception as e_disc: print(f"Error disconnecting {session_path_str}: {e_disc}")
        telethon_session_lock.release();
    return messages_for_ratios

async def update_features_and_predictions_job():
    print(f"[{datetime.now()}] Starting daily feature and prediction update job...")
    with app.app_context():
        try:
            sentiment_pipeline = get_sentiment_pipeline();
            if sentiment_pipeline is None: print(" Sentiment pipeline N/A."); return
            btc_df = get_btc_data(days=max(170, SEQUENCE_LENGTH + 100));
            if btc_df.empty: print("BTC data fetch failed."); return
            btc_df['date_obj'] = pd.to_datetime(btc_df['date']).dt.date
            end_date_sentiment = datetime.now(); start_date_sentiment = end_date_sentiment - timedelta(days=MESSAGE_LOOKBACK_DAYS)
            tg_msgs_for_ratios = await scrape_telegram_messages(start_date_sentiment, end_date_sentiment, TELEGRAM_GROUPS_CONFIG, "telegram_scraper_db_update", sentiment_pipeline, store_messages_in_db=True)
            rd_items_for_ratios = await asyncio.to_thread(fetch_reddit_bitcoin_data, start_date_sentiment, sentiment_pipeline, store_in_db=True)
            sentiment_ratios_df, _ = prepare_sentiment_data(tg_msgs_for_ratios + rd_items_for_ratios)
            if not sentiment_ratios_df.empty:
                sentiment_ratios_df['date_obj'] = pd.to_datetime(sentiment_ratios_df['date']).dt.date
                combined_df = pd.merge(btc_df, sentiment_ratios_df[['date_obj', 'positive_ratio', 'negative_ratio', 'neutral_ratio']], on='date_obj', how='left')
            else: combined_df = btc_df.copy(); combined_df['positive_ratio']=0.0; combined_df['negative_ratio']=0.0; combined_df['neutral_ratio']=1.0
            for col in ['positive_ratio', 'negative_ratio', 'neutral_ratio']: combined_df[col] = combined_df[col].ffill().bfill().fillna(1.0 if col == 'neutral_ratio' else 0.0)
            for f_col in features:
                if f_col not in combined_df.columns: combined_df[f_col] = 0.0
            combined_df[features] = combined_df[features].ffill().bfill().fillna(0)

            update_cnt, insert_cnt = 0, 0; cutoff_db_date = (datetime.now() - timedelta(days=180 + PREDICTION_HORIZON)).date()
            combined_df.rename(columns={'date_obj': 'feature_date'}, inplace=True)
            relevant_df = combined_df[combined_df['feature_date'] >= cutoff_db_date].copy(); relevant_df.sort_values(by='feature_date', inplace=True)
            last_known_date = relevant_df['feature_date'].max();
            if pd.isna(last_known_date): last_known_date = (datetime.now() - timedelta(days=1)).date()
            if isinstance(last_known_date, pd.Timestamp): last_known_date = last_known_date.date()

            today_date = datetime.now().date()
            if not DailyFeatures.query.filter_by(date=today_date).first():
                if today_date > last_known_date or not relevant_df[relevant_df['feature_date'] == today_date].empty:
                    is_today_in_relevant = not relevant_df[relevant_df['feature_date'] == today_date].empty
                    if not is_today_in_relevant :
                        placeholder_today = DailyFeatures(date=today_date)
                        for f_n in features: setattr(placeholder_today, f_n, None)
                        db.session.add(placeholder_today)
                        insert_cnt +=1

            for i in range(PREDICTION_HORIZON + 1):
                future_date_obj = last_known_date + timedelta(days=i)
                if not DailyFeatures.query.filter_by(date=future_date_obj).first():
                    placeholder_feature = DailyFeatures(date=future_date_obj); [setattr(placeholder_feature, f_n, None) for f_n in features]
                    db.session.add(placeholder_feature); insert_cnt +=1
            db.session.commit()

            for _, row in relevant_df.iterrows():
                rec_date = row['feature_date']
                if pd.isna(rec_date): continue
                if isinstance(rec_date, pd.Timestamp): rec_date = rec_date.date()

                existing_feature = DailyFeatures.query.filter_by(date=rec_date).first()
                feature_values = {}
                for f_name in features:
                    val_from_row = row.get(f_name)
                    if pd.isna(val_from_row) or (isinstance(val_from_row, float) and math.isnan(val_from_row)): feature_values[f_name] = None
                    elif isinstance(val_from_row, (np.int64, int)): feature_values[f_name] = int(val_from_row)
                    elif isinstance(val_from_row, (np.float64, float)): feature_values[f_name] = float(val_from_row)
                    else: feature_values[f_name] = None

                if existing_feature:
                    changed = False
                    for fn_name, val_in in feature_values.items():
                        current_val_db = getattr(existing_feature, fn_name, None)
                        is_different = False
                        if val_in is None and current_val_db is not None: is_different = True
                        elif val_in is not None and current_val_db is None: is_different = True
                        elif isinstance(val_in, float) and (current_val_db is None or not isinstance(current_val_db, float) or not np.isclose(val_in, float(current_val_db), equal_nan=True)): is_different = True
                        elif isinstance(val_in, int) and (current_val_db is None or not isinstance(current_val_db, int) or val_in != int(current_val_db)): is_different = True
                        if is_different: setattr(existing_feature, fn_name, val_in); changed = True
                    if changed: update_cnt += 1
                else:
                    new_feature_rec = DailyFeatures(date=rec_date, **feature_values); db.session.add(new_feature_rec); insert_cnt += 1
            db.session.commit(); print(f"DailyFeatures DB: Inserted {insert_cnt}, Updated {update_cnt}.")

            model, scaler = get_model_and_scaler()
            if model is None: print("Keras model not loaded."); return
            db_features_for_pred = DailyFeatures.query.order_by(DailyFeatures.date.desc()).limit(SEQUENCE_LENGTH + 60).all()
            if not db_features_for_pred or len(db_features_for_pred) < SEQUENCE_LENGTH: print(f" Not enough DailyFeatures ({len(db_features_for_pred)}) for pred."); return

            hist_data_list = []
            for r_item in reversed(db_features_for_pred):
                record = {'date': r_item.date}
                for f_col_name in features:
                    val = getattr(r_item, f_col_name, 0.0)
                    record[f_col_name] = 0.0 if val is None or (isinstance(val, float) and math.isnan(val)) else float(val)
                hist_data_list.append(record)
            hist_data_for_pred_df = pd.DataFrame(hist_data_list)

            _, avg_confidences_by_day_step, _ = calculate_historical_predictions_and_confidence(hist_data_for_pred_df.copy(), features, model, scaler, seq_len=SEQUENCE_LENGTH, test_period_days=30, pred_horizon=PREDICTION_HORIZON)

            input_df_for_prediction_raw = hist_data_for_pred_df[hist_data_for_pred_df['date'] <= last_known_date].copy()
            for f_col in features:
                if f_col not in input_df_for_prediction_raw.columns:
                    input_df_for_prediction_raw[f_col] = 0.0
                input_df_for_prediction_raw[f_col] = pd.to_numeric(input_df_for_prediction_raw[f_col], errors='coerce').fillna(0.0)

            if len(input_df_for_prediction_raw) < SEQUENCE_LENGTH:
                 print(f"Final check: Not enough data ({len(input_df_for_prediction_raw)}) for predict_multistep. Need {SEQUENCE_LENGTH}.")
                 return

            predicted_prices_raw, prediction_target_dates_dt = predict_bitcoin_prices_multistep(input_df_for_prediction_raw, features, model, scaler, seq_len=SEQUENCE_LENGTH, pred_horizon=PREDICTION_HORIZON)

            print("\n--- Generated Predictions ---")
            temp_current_price_for_signal = input_df_for_prediction_raw['close'].iloc[-1]
            for k_idx, dt_val in enumerate(prediction_target_dates_dt):
                p_price = predicted_prices_raw[k_idx]
                p_diff_temp = p_price - temp_current_price_for_signal
                p_sig_temp = "hold"
                if p_diff_temp > HOLD_THRESHOLD_USD: p_sig_temp = "buy"
                elif p_diff_temp < -HOLD_THRESHOLD_USD: p_sig_temp = "sell"
                p_chg_temp = ((p_price - temp_current_price_for_signal) / temp_current_price_for_signal) * 100 if temp_current_price_for_signal !=0 else 0
                conf_temp = float(avg_confidences_by_day_step.get(str(k_idx + 1), 50.0))
                mape_temp = 100.0 - conf_temp
                print(f"Day +{k_idx+1}: {dt_val.strftime('%Y-%m-%d'):<12} ${p_price:>14,.2f} ({p_sig_temp.upper():<4}) Diff: ${p_diff_temp:>+8.2f} ({p_chg_temp:>+7.2f}%) | Conf: {conf_temp:>4.1f}% | MAPE: {mape_temp:>4.1f}%")
                temp_current_price_for_signal = p_price
            print("---------------------------\n")

            last_feature_entry_for_pred = DailyFeatures.query.filter_by(date=last_known_date).first()
            if not last_feature_entry_for_pred: print(f"Error: Could not find DailyFeatures for base date {last_known_date}."); return

            current_price_for_signal = input_df_for_prediction_raw['close'].iloc[-1]
            prediction_stored_count = 0
            for i in range(len(prediction_target_dates_dt)):
                target_date_pred = prediction_target_dates_dt[i].date()
                pred_price = float(predicted_prices_raw[i])
                target_daily_feature = DailyFeatures.query.filter_by(date=target_date_pred).first()
                if not target_daily_feature:
                    print(f"Warning: No DailyFeatures placeholder for {target_date_pred}. Creating."); target_daily_feature = DailyFeatures(date=target_date_pred); db.session.add(target_daily_feature);
                price_diff = pred_price - current_price_for_signal; signal = "hold"
                if price_diff > HOLD_THRESHOLD_USD: signal = "buy"
                elif price_diff < -HOLD_THRESHOLD_USD: signal = "sell"
                confidence_for_this_step = float(avg_confidences_by_day_step.get(str(i + 1), 50.0))
                existing_prediction = ModelPredictions.query.filter_by(prediction_date_fk_val=target_date_pred, base_features_date=last_known_date).first()
                if existing_prediction:
                    existing_prediction.predicted_price = pred_price; existing_prediction.signal = signal; existing_prediction.confidence = confidence_for_this_step
                else:
                    new_prediction = ModelPredictions(prediction_date_fk_val=target_date_pred, base_features_date=last_known_date, predicted_price=pred_price, signal=signal, confidence=confidence_for_this_step)
                    db.session.add(new_prediction)
                current_price_for_signal = pred_price; prediction_stored_count +=1
            db.session.commit(); print(f" Stored/Updated {prediction_stored_count} model predictions.")
        except Exception as e: db.session.rollback(); print(f"Daily feature/prediction job error: {e}"); traceback.print_exc()

def prepare_sentiment_data(sentiment_messages):
    if not sentiment_messages:
        today = pd.to_datetime(datetime.now().date())
        return pd.DataFrame([{'date': today, 'positive_ratio': 0.0, 'negative_ratio': 0.0, 'neutral_ratio': 1.0}]), pd.DataFrame([{'date': today, 'sentiment_score': 50.0}])

    df = pd.DataFrame(sentiment_messages)
    df['date_dt'] = pd.to_datetime(df['date'])
    df['date_only'] = df['date_dt'].dt.normalize()
    if 'source' not in df.columns: df['source'] = 'unknown'

    df['weight'] = 1.0
    if 'score' in df.columns and df['source'].str.contains('reddit', case=False, na=False).any():
        mask = df['source'].str.contains('reddit', case=False, na=False) & df['score'].notna()
        if mask.any():
            scores = df.loc[mask, 'score'].astype(float)
            min_s, max_s = scores.min(), max(1.0, scores.max())
            normalized_scores = scores.clip(upper=max_s * 2) / (max_s * 2 if max_s > 0 else 1.0)
            df.loc[mask, 'weight'] = 1.0 + 2.0 * normalized_scores

    neutrals = df[df['sentiment'] == 'Neutral']
    if not neutrals.empty:
        drop_idx = []
        for _, group in neutrals.groupby([df.loc[neutrals.index, 'date_only'], df.loc[neutrals.index, 'source']]):
            if len(group) > 10:
                drop_count = int(len(group) * 0.7)
                if drop_count > 0:
                    drop_idx.extend(group.sample(n=drop_count, random_state=1).index)
        if drop_idx:
            df.drop(index=drop_idx, inplace=True)

    if df.empty:
        return prepare_sentiment_data([])

    def calculate_ratios(g):
        total_weight = g['weight'].sum()
        if total_weight == 0: return pd.Series({'positive_ratio': 0.0, 'negative_ratio': 0.0, 'neutral_ratio': 1.0})
        pos_w = g[g['sentiment'] == 'Positive']['weight'].sum()
        neg_w = g[g['sentiment'] == 'Negative']['weight'].sum()
        neu_w = g[g['sentiment'] == 'Neutral']['weight'].sum()
        p, n, u = normalize_sentiment_ratios(pos_w, neg_w, neu_w)
        return pd.Series({'positive_ratio': p / 100.0, 'negative_ratio': n / 100.0, 'neutral_ratio': u / 100.0})

    sentiment_ratios_df = df.groupby('date_only', group_keys=False).apply(calculate_ratios).reset_index().rename(columns={'date_only': 'date'})

    def calculate_score(g):
        total_weight = g['weight'].sum()
        if total_weight == 0: return pd.Series({'sentiment_score': 50.0})
        pos_w = g[g['sentiment'] == 'Positive']['weight'].sum()
        neg_w = g[g['sentiment'] == 'Negative']['weight'].sum()
        raw_score = (pos_w - neg_w) / total_weight if total_weight > 0 else 0
        return pd.Series({'sentiment_score': (raw_score + 1) * 50})

    sentiment_timeline_df = df.groupby('date_only', group_keys=False).apply(calculate_score).reset_index().rename(columns={'date_only': 'date'})
    sentiment_timeline_df.sort_values(by='date', inplace=True)

    return sentiment_ratios_df, sentiment_timeline_df

def get_model_and_scaler():
    global _model_cache, _scaler_cache
    if _model_cache is None:
        if not os.path.exists(MODEL_PATH): raise FileNotFoundError(f"Model file {MODEL_PATH} not found!")
        try: _model_cache = load_model(MODEL_PATH); print(f"Model loaded: {MODEL_PATH}")
        except Exception as e: print(f"Model load error: {e}"); _model_cache = None; raise
    if _scaler_cache is None:
        if os.path.exists(SCALER_PATH):
            try:
                _scaler_cache = joblib.load(SCALER_PATH); print(f"Scaler loaded: {SCALER_PATH}")
                if not hasattr(_scaler_cache, 'transform') or not hasattr(_scaler_cache, 'inverse_transform'): print(f"⚠️ Loaded obj from {SCALER_PATH} not valid scaler."); _scaler_cache = None
                elif not hasattr(_scaler_cache, 'feature_names_in_') or _scaler_cache.feature_names_in_ is None:
                     print(f" Scaler {SCALER_PATH} lacks 'feature_names_in_' or it's None. Will rely on feature order or re-fit if needed.")
                elif _scaler_cache.feature_names_in_ is not None: print(f"   Scaler features (first 5): {list(_scaler_cache.feature_names_in_[:5])}... ({len(_scaler_cache.feature_names_in_)} total)")
            except Exception as e: print(f"Scaler load error: {e}."); _scaler_cache = None
        else: print(f" Scaler file {SCALER_PATH} not found. Will create new if needed."); _scaler_cache = None
    return _model_cache, _scaler_cache

def predict_bitcoin_prices_multistep(history_df_input, features_list_model_expects, model_obj, scaler_obj=None, seq_len=SEQUENCE_LENGTH, pred_horizon=PREDICTION_HORIZON):
    history_df = history_df_input.copy()
    if len(history_df) < seq_len: raise ValueError(f"Not enough data. Need {seq_len}, got {len(history_df)}.")
    if 'date' in history_df.columns and not pd.api.types.is_datetime64_any_dtype(history_df['date']): history_df['date'] = pd.to_datetime(history_df['date'])
    elif 'date' not in history_df.columns: history_df['date'] = pd.to_datetime(datetime.now().date()) - pd.to_timedelta(np.arange(len(history_df) -1, -1, -1), unit='D')

    current_scaler = scaler_obj
    features_for_scaling = [f for f in features_list_model_expects if f in history_df.columns and pd.api.types.is_numeric_dtype(history_df[f])]
    if not features_for_scaling: raise ValueError("No numeric features in history_df for scaling.")

    if current_scaler is None:
        print("--- Creating and fitting new MinMaxScaler ---")
        current_scaler = MinMaxScaler(feature_range=(0, 1))
        current_scaler.fit(history_df[features_for_scaling].values)
        setattr(current_scaler, 'n_features_in_', len(features_for_scaling))
        setattr(current_scaler, 'feature_names_in_', np.array(features_for_scaling, dtype=object))
        print(f"New scaler fitted on features: {features_for_scaling}")
        try:
            joblib.dump(current_scaler, SCALER_PATH)
            print(f" Newly fitted scaler saved to {SCALER_PATH}")
        except Exception as e_save_scaler:
            print(f" Error saving newly fitted scaler: {e_save_scaler}")
        global _scaler_cache
        _scaler_cache = current_scaler

    scaler_fit_features = []
    if hasattr(current_scaler, 'feature_names_in_') and current_scaler.feature_names_in_ is not None:
        scaler_fit_features = list(current_scaler.feature_names_in_)
    else:
        scaler_fit_features = features_for_scaling
        print(f" Scaler lacks 'feature_names_in_'. Relying on current features_for_scaling: {scaler_fit_features[:5]}")

    if not scaler_fit_features:
        raise ValueError("Critical error: scaler_fit_features is empty. Cannot proceed with scaling.")

    missing_in_hist = [f for f in scaler_fit_features if f not in history_df.columns]
    if missing_in_hist: raise ValueError(f"Scaler fit on features {missing_in_hist} not in history_df for transform.")

    last_sequence_data_for_transform = history_df.loc[history_df.index[-seq_len:], scaler_fit_features].values

    if last_sequence_data_for_transform.shape[1] != len(scaler_fit_features): raise ValueError(f"Shape mismatch before transform: Expected {len(scaler_fit_features)} cols, got {last_sequence_data_for_transform.shape[1]}.")
    last_sequence_scaled = current_scaler.transform(last_sequence_data_for_transform)

    model_input_sequence = np.zeros((1, seq_len, len(features_list_model_expects)))
    for model_feature_idx, model_feature_name in enumerate(features_list_model_expects):
        if model_feature_name in scaler_fit_features:
            try:
                idx_in_scaled_data = scaler_fit_features.index(model_feature_name)
                model_input_sequence[0, :, model_feature_idx] = last_sequence_scaled[:, idx_in_scaled_data]
            except ValueError: model_input_sequence[0, :, model_feature_idx] = 0.0
        elif model_feature_name in history_df.columns:
            model_input_sequence[0, :, model_feature_idx] = history_df.iloc[-seq_len:][model_feature_name].values
        else: model_input_sequence[0, :, model_feature_idx] = 0.0

    predictions_scaled_model_output = model_obj.predict(model_input_sequence, verbose=0)[0]
    future_prices = []
    if 'close' not in scaler_fit_features:
        print("CRITICAL: 'close' was not part of scaler_fit_features. Assuming model predicts unscaled 'close'.")
        if features_list_model_expects[0] == 'close':
            if predictions_scaled_model_output.ndim == 1 and len(predictions_scaled_model_output) == pred_horizon: future_prices = predictions_scaled_model_output
            elif predictions_scaled_model_output.ndim == 2 and predictions_scaled_model_output.shape[0] == pred_horizon and predictions_scaled_model_output.shape[1] == 1: future_prices = predictions_scaled_model_output.flatten()
            elif predictions_scaled_model_output.ndim == 2: future_prices = predictions_scaled_model_output[:, 0]
            else: raise ValueError("Cannot determine unscaled 'close' prices from model output shape.")
        else: raise ValueError("'close' not scaled & not primary model output. Cannot determine prices.")
    else:
        close_idx_in_scaler_fit = scaler_fit_features.index('close')
        dummy_array_for_inverse = np.zeros((pred_horizon, len(scaler_fit_features)))
        if predictions_scaled_model_output.ndim == 1 and len(predictions_scaled_model_output) == pred_horizon: scaled_close_predictions = predictions_scaled_model_output
        elif predictions_scaled_model_output.ndim == 2 and predictions_scaled_model_output.shape[0] == pred_horizon:
            scaled_close_predictions = predictions_scaled_model_output[:, 0]
        else: raise ValueError(f"Unhandled model output shape for 'close' prediction: {predictions_scaled_model_output.shape}.")
        dummy_array_for_inverse[:, close_idx_in_scaler_fit] = scaled_close_predictions
        inversed_predictions_all_features = current_scaler.inverse_transform(dummy_array_for_inverse)
        future_prices = inversed_predictions_all_features[:, close_idx_in_scaler_fit]

    last_date_in_history = history_df['date'].iloc[-1]
    prediction_dates = [last_date_in_history + timedelta(days=i + 1) for i in range(pred_horizon)]
    return future_prices, prediction_dates

def calculate_historical_predictions_and_confidence(data_df_input, features_list, model_obj, scaler_obj, seq_len=SEQUENCE_LENGTH, test_period_days=30, pred_horizon=PREDICTION_HORIZON):
    data_df = data_df_input.copy(); results = []
    if 'date' in data_df.columns and not pd.api.types.is_datetime64_any_dtype(data_df['date']): data_df['date'] = pd.to_datetime(data_df['date'])
    elif 'date' not in data_df.columns: data_df['date'] = pd.to_datetime(datetime.now().date()) - pd.to_timedelta(np.arange(len(data_df)-1, -1, -1), unit='D')
    if len(data_df) < test_period_days + seq_len + pred_horizon:
        test_period_days = max(0, len(data_df) - seq_len - pred_horizon)
        if test_period_days == 0:
            return pd.DataFrame(results), {str(i): 50.0 for i in range(1, pred_horizon + 1)}, {str(i): 50.0 for i in range(1, pred_horizon + 1)}
    mapes_by_day_step = {i: [] for i in range(1, pred_horizon + 1)}
    for i in range(test_period_days):
        prediction_point_idx = len(data_df) - 1 - pred_horizon - i
        if prediction_point_idx < seq_len -1 : continue
        segment_df = data_df.iloc[:prediction_point_idx + 1].copy()
        if len(segment_df) < seq_len: continue
        actual_values = [data_df['close'].iloc[prediction_point_idx + 1 + j] if prediction_point_idx + 1 + j < len(data_df) else np.nan for j in range(pred_horizon)]
        try:
            predicted_prices, _ = predict_bitcoin_prices_multistep(segment_df, features_list, model_obj, scaler_obj, seq_len, pred_horizon)
            row_results = {'base_date': segment_df['date'].iloc[-1]}
            for day_step_ahead in range(pred_horizon):
                actual_val, pred_val = actual_values[day_step_ahead], predicted_prices[day_step_ahead]
                current_mape = np.nan
                if pd.notna(actual_val) and pd.notna(pred_val) and actual_val != 0: current_mape = abs((actual_val - pred_val) / actual_val) * 100; mapes_by_day_step[day_step_ahead + 1].append(current_mape)
                row_results.update({f'predicted_day_{day_step_ahead + 1}': pred_val, f'actual_day_{day_step_ahead + 1}': actual_val, f'mape_day_{day_step_ahead + 1}': current_mape})
            results.append(row_results)
        except ValueError as ve: print(f"Hist pred ValueError iter {i} (base: {segment_df['date'].iloc[-1].date()}): {ve}")
        except Exception as e: print(f"Hist pred general error iter {i} (base: {segment_df['date'].iloc[-1].date()}): {e}")
    results_df = pd.DataFrame(results); avg_mapes_output, avg_confs_output = {}, {}
    for day_step_num in range(1, pred_horizon + 1):
        mapes_for_step = mapes_by_day_step.get(day_step_num, []); valid_mapes = [m for m in mapes_for_step if pd.notna(m)]
        avg_mape = np.mean(valid_mapes) if valid_mapes else 50.0
        avg_mapes_output[str(day_step_num)] = round(avg_mape, 2); avg_confs_output[str(day_step_num)] = round(min(99.9, max(0.0, 100 - avg_mape)), 1)
    if not results_df.empty: print("\nAvg Hist MAPE:", {k: f"{v}%" for k,v in avg_mapes_output.items()}); print("Derived Avg Conf:", {k: f"{v}%" for k,v in avg_confs_output.items()})
    return results_df, avg_confs_output, avg_mapes_output

def get_sentiment_pipeline():
    global _sentiment_pipeline_cache_obj
    if _sentiment_pipeline_cache_obj is None:
        device_num = 0 if torch.cuda.is_available() else -1; device_name = f"cuda:{device_num}" if device_num != -1 else "cpu"
        print(f"Sentiment analysis device: {device_name}"); model_name = "yiyanghkust/finbert-tone"
        try:
            tokenizer = AutoTokenizer.from_pretrained(model_name); model_obj_sent = AutoModelForSequenceClassification.from_pretrained(model_name)
            if device_num != -1 : model_obj_sent = model_obj_sent.to(torch.device(device_name))
            _sentiment_pipeline_cache_obj = pipeline("sentiment-analysis", model=model_obj_sent, tokenizer=tokenizer, device=device_num); print(" Sentiment pipeline initialized.")
        except Exception as e:
            print(f" Sentiment pipeline init error ({model_name}): {e}"); print("Attempting fallback...")
            try:
                model_name_fallback = "distilbert-base-uncased-finetuned-sst-2-english"
                tokenizer = AutoTokenizer.from_pretrained(model_name_fallback); model_obj_sent_fallback = AutoModelForSequenceClassification.from_pretrained(model_name_fallback)
                if device_num != -1 : model_obj_sent_fallback = model_obj_sent_fallback.to(torch.device(device_name))
                _sentiment_pipeline_cache_obj = pipeline("sentiment-analysis", model=model_obj_sent_fallback, tokenizer=tokenizer, device=device_num); print(f"Fallback pipeline ({model_name_fallback}) initialized.")
            except Exception as e_fallback: print(f" Fallback pipeline failed: {e_fallback}"); _sentiment_pipeline_cache_obj = None
    return _sentiment_pipeline_cache_obj

@app.route('/api/predict', methods=['POST'])
async def api_predict_route():
    try:
        current_btc_price = 0.0
        try:
            resp_cg = requests.get("https://api.coingecko.com/api/v3/simple/price", params={"ids": "bitcoin", "vs_currencies": "usd"})
            resp_cg.raise_for_status(); current_btc_price = float(resp_cg.json()["bitcoin"]["usd"])
        except Exception as e_cg:
            print(f"CoinGecko price error: {e_cg}. Using DB fallback.")
            latest_feature = DailyFeatures.query.order_by(DailyFeatures.date.desc()).first()
            if latest_feature and latest_feature.close is not None: current_btc_price = latest_feature.close
            else: return jsonify(replace_nan_with_none({"error": "Failed to fetch current BTC price."})), 500

        latest_base_date_entry = db.session.query(func.max(ModelPredictions.base_features_date)).scalar()
        predictions_list = []
        if latest_base_date_entry:
            today_date_val = datetime.now().date()
            stored_preds = ModelPredictions.query.filter(ModelPredictions.base_features_date == latest_base_date_entry, ModelPredictions.prediction_date_fk_val >= today_date_val).order_by(ModelPredictions.prediction_date_fk_val.asc()).limit(PREDICTION_HORIZON).all()
            prev_p_for_change = current_btc_price
            for idx, pred_obj in enumerate(stored_preds):
                pred_price_val = float(pred_obj.predicted_price) if pred_obj.predicted_price is not None else 0.0
                change_pct = ((pred_price_val - prev_p_for_change) / prev_p_for_change) * 100 if prev_p_for_change != 0 else 0.0
                predictions_list.append({'date': pred_obj.prediction_date_fk_val.strftime('%Y-%m-%d'), 'predicted_price': pred_price_val, 'change_percent': round(change_pct, 2), 'signal_type': pred_obj.signal, 'confidence': round(float(pred_obj.confidence), 1) if pred_obj.confidence is not None else 50.0, 'mape': round(max(0.0, 100.0 - (float(pred_obj.confidence) if pred_obj.confidence is not None else 50.0)), 1), 'day_number': idx + 1})
                prev_p_for_change = pred_price_val

        latest_daily_feature = DailyFeatures.query.order_by(DailyFeatures.date.desc()).first()
        sentiment_summary = {'positive': 0.0, 'negative': 0.0, 'neutral': 100.0, 'score': 50, 'label': 'Neutral'}
        if latest_daily_feature:
            p_r_raw = latest_daily_feature.positive_ratio if latest_daily_feature.positive_ratio is not None else 0.0
            n_r_raw = latest_daily_feature.negative_ratio if latest_daily_feature.negative_ratio is not None else 0.0
            u_r_raw = latest_daily_feature.neutral_ratio if latest_daily_feature.neutral_ratio is not None else 0.0


            p_perc, n_perc, u_perc = normalize_sentiment_ratios(p_r_raw, n_r_raw, u_r_raw)

            raw_score_for_display = ((p_r_raw - n_r_raw) + 1) * 50

            sentiment_label_for_display = 'Neutral'
            if raw_score_for_display > 60 : sentiment_label_for_display = 'Positive'
            elif raw_score_for_display < 40 : sentiment_label_for_display = 'Negative'

            sentiment_summary = {
                'positive': p_perc,
                'negative': n_perc,
                'neutral': u_perc,
                'score': round(raw_score_for_display,1),
                'label': sentiment_label_for_display
            }

        hist_prices_records = DailyFeatures.query.filter(DailyFeatures.date <= datetime.now().date()).order_by(DailyFeatures.date.asc()).limit(30).all()
        hist_prices_for_chart = [{'x': r.date.strftime('%Y-%m-%d'), 'y': r.close if r.close is not None else None} for r in hist_prices_records]
        current_date_str_for_chart = datetime.now().date().strftime('%Y-%m-%d')
        if hist_prices_for_chart and hist_prices_for_chart[-1]['x'] == current_date_str_for_chart:
            hist_prices_for_chart[-1]['y'] = current_btc_price
        elif not hist_prices_for_chart or hist_prices_for_chart[-1]['x'] < current_date_str_for_chart:
            hist_prices_for_chart.append({'x': current_date_str_for_chart, 'y': current_btc_price})

        news_items_db = TelegramMessage.query.order_by(desc(TelegramMessage.message_date)).limit(15).all()
        news_payload = [{'date': msg.message_date.isoformat(), 'text': msg.message_text, 'sentiment': msg.sentiment_label, 'source': 'telegram', 'group': msg.source_group} for msg in news_items_db]

        sentiment_timeline_records_db = DailyFeatures.query.order_by(DailyFeatures.date.desc()).limit(30).all()
        sentiment_timeline_payload = {
            "dates": [],
            "positive_ratios": [],
            "negative_ratios": [],
            "neutral_ratios": [],
            "scores": []
        }
        for r_sent_timeline in reversed(sentiment_timeline_records_db):
            sentiment_timeline_payload["dates"].append(r_sent_timeline.date.strftime('%Y-%m-%d'))

            p_raw_tl = r_sent_timeline.positive_ratio if r_sent_timeline.positive_ratio is not None else 0.0
            n_raw_tl = r_sent_timeline.negative_ratio if r_sent_timeline.negative_ratio is not None else 0.0
            u_raw_tl = r_sent_timeline.neutral_ratio if r_sent_timeline.neutral_ratio is not None else 0.0 # Default to 0 if not present to allow normalization

            p_perc_tl, n_perc_tl, u_perc_tl = normalize_sentiment_ratios(p_raw_tl, n_raw_tl, u_raw_tl)

            sentiment_timeline_payload["positive_ratios"].append(p_perc_tl)
            sentiment_timeline_payload["negative_ratios"].append(n_perc_tl)
            sentiment_timeline_payload["neutral_ratios"].append(u_perc_tl)

            score_tl = ((p_raw_tl - n_raw_tl) + 1) * 50
            sentiment_timeline_payload["scores"].append(round(score_tl, 2) if pd.notna(score_tl) else 50.0)

        ti_chart_records_db = DailyFeatures.query.order_by(DailyFeatures.date.desc()).limit(100).all()
        ti_data_list_payload = []
        if ti_chart_records_db:
            for r_ti_db in reversed(ti_chart_records_db):
                record_dict_ti = {'date': r_ti_db.date.strftime('%Y-%m-%d')}
                for f_ti_name in features:
                    val_ti = getattr(r_ti_db, f_ti_name, None)
                    record_dict_ti[f_ti_name] = None if isinstance(val_ti, float) and math.isnan(val_ti) else val_ti
                ti_data_list_payload.append(record_dict_ti)

        ti_chart_df_from_db_payload = pd.DataFrame(ti_data_list_payload)
        ti_payload_final = {"labels": [], "price_data": [], "current_values": {}}
        current_ta_values_payload = {}

        if not ti_chart_df_from_db_payload.empty:
            ti_payload_final["labels"] = ti_chart_df_from_db_payload['date'].tolist()
            ti_payload_final["price_data"] = [p_val if pd.notna(p_val) else None for p_val in ti_chart_df_from_db_payload['close'].tolist()]

            indicators_to_chart_map = {"rsi_data": "RSI", "bollinger_upper_data": "Bollinger_Upper", "bollinger_lower_data": "Bollinger_Lower", "volatility_data": "Volatility", "sma_20_data": "SMA_20"}
            latest_ti_record_from_df = ti_chart_df_from_db_payload.iloc[-1] if not ti_chart_df_from_db_payload.empty else pd.Series(dtype=object)

            price_for_ti_calc = latest_ti_record_from_df.get('close')
            current_ta_values_payload['current_price_for_ti'] = float(price_for_ti_calc) if pd.notna(price_for_ti_calc) else None

            for key_frontend, col_name_in_db in indicators_to_chart_map.items():
                if col_name_in_db in ti_chart_df_from_db_payload:
                    ti_payload_final[key_frontend] = [v_ti if pd.notna(v_ti) else None for v_ti in ti_chart_df_from_db_payload[col_name_in_db].tolist()]
                    last_val_ti_from_df = latest_ti_record_from_df.get(col_name_in_db)
                    current_ta_values_payload[col_name_in_db.lower()] = float(last_val_ti_from_df) if pd.notna(last_val_ti_from_df) else None
                else:
                    ti_payload_final[key_frontend] = [None] * len(ti_chart_df_from_db_payload)
                    current_ta_values_payload[col_name_in_db.lower()] = None
        ti_payload_final["current_values"] = current_ta_values_payload

        historical_analysis_summary_payload = {'avg_confidence': {str(p_item['day_number']): p_item['confidence'] for p_item in predictions_list},
                                          'avg_mape': {str(p_item['day_number']): p_item['mape'] for p_item in predictions_list}}

        final_response_data = {
            'current_price': current_btc_price,
            'predictions': predictions_list,
            'historical_analysis': historical_analysis_summary_payload,
            'sentiment_summary': sentiment_summary,
            'historical_prices_for_chart': hist_prices_for_chart,
            'news_items': news_payload,
            'sentiment_timeline': sentiment_timeline_payload,
            'technical_indicators_data': ti_payload_final,
            'telegram_sentiment_summary': None,
            'reddit_sentiment_summary': None
        }
        cleaned_response_data = replace_nan_with_none(final_response_data)
        return jsonify(cleaned_response_data)
    except Exception as e: print(f"Error in /api/predict: {e}"); traceback.print_exc(); return jsonify(replace_nan_with_none({"error": "Internal server error", "details": str(e)})), 500

@app.route('/api/news', methods=['GET'])
async def api_get_news():
    try:
        limit = request.args.get('limit', default=25, type=int); limit = max(5, min(limit, 100))
        with app.app_context():
            tg_messages_db = TelegramMessage.query.order_by(desc(TelegramMessage.message_date)).limit(limit // 2 + 5).all()
            rd_messages_db = RedditMessage.query.order_by(desc(RedditMessage.message_date)).limit(limit // 2 + 5).all()
        news_items_list = []
        for m_tg in tg_messages_db: news_items_list.append({'date': m_tg.message_date.isoformat(), 'text': m_tg.message_text, 'sentiment': m_tg.sentiment_label, 'source': 'Telegram', 'group': m_tg.source_group, 'id': f"tg_{m_tg.id}"})
        for m_rd in rd_messages_db: news_items_list.append({'date': m_rd.message_date.isoformat(), 'text': m_rd.message_text, 'sentiment': m_rd.sentiment_label, 'source': 'Reddit', 'group_or_subreddit': f"r/{m_rd.subreddit}" + (f" ({m_rd.source_platform.split('_')[-1]})" if m_rd.source_platform else ""), 'id': f"rd_{m_rd.id}"})
        news_items_list.sort(key=lambda x: x['date'], reverse=True); final_news_list = news_items_list[:limit]
        cleaned_news_list = replace_nan_with_none(final_news_list)
        return jsonify(cleaned_news_list)
    except Exception as e: print(f"Error in /api/news: {e}"); traceback.print_exc(); return jsonify(replace_nan_with_none({"error": "News retrieval error", "details": str(e)})), 500

@app.route('/api/sentiment-timeline', methods=['GET'])
async def api_get_sentiment_timeline():
    try:
        days = request.args.get('days', default=30, type=int); days = max(1, min(days, 180))
        with app.app_context():
            start_date_db_query = (datetime.now() - timedelta(days=days)).date()
            sentiment_records_db = DailyFeatures.query.filter(DailyFeatures.date >= start_date_db_query).order_by(DailyFeatures.date.asc()).all()

        output_timeline_list_api = []
        overall_positive_sum_ratio = 0.0
        overall_negative_sum_ratio = 0.0
        overall_neutral_sum_ratio = 0.0
        record_count = 0

        if sentiment_records_db:
            for record_item in sentiment_records_db:
                pos_r_api_raw = record_item.positive_ratio if record_item.positive_ratio is not None else 0.0
                neg_r_api_raw = record_item.negative_ratio if record_item.negative_ratio is not None else 0.0
                neu_r_api_raw = record_item.neutral_ratio if record_item.neutral_ratio is not None else 0.0

                score_api = ((pos_r_api_raw - neg_r_api_raw) + 1) * 50
                output_timeline_list_api.append({'date': record_item.date.strftime('%Y-%m-%d'), 'score': round(score_api, 2) if pd.notna(score_api) else None})

                overall_positive_sum_ratio += pos_r_api_raw
                overall_negative_sum_ratio += neg_r_api_raw
                overall_neutral_sum_ratio += neu_r_api_raw if record_item.neutral_ratio is not None else (1.0 - pos_r_api_raw - neg_r_api_raw)
                record_count += 1

        avg_p_perc, avg_n_perc, avg_u_perc = 0.0, 0.0, 100.0
        if record_count > 0:
            avg_p_ratio_raw = overall_positive_sum_ratio / record_count
            avg_n_ratio_raw = overall_negative_sum_ratio / record_count
            avg_u_ratio_raw = overall_neutral_sum_ratio / record_count

            avg_p_perc, avg_n_perc, avg_u_perc = normalize_sentiment_ratios(avg_p_ratio_raw, avg_n_ratio_raw, avg_u_ratio_raw)

        overall_sentiment_ratios_api = {'positive': avg_p_perc, 'negative': avg_n_perc, 'neutral': avg_u_perc}

        current_analysis_api = {'overall_sentiment': 'Neutral', 'trend': 'Stable', **overall_sentiment_ratios_api}

        if output_timeline_list_api:
            scores = [s['score'] for s in output_timeline_list_api if s['score'] is not None]
            if len(scores) >= 2:
                mid = len(scores) // 2
                if mid > 0:
                    avg1 = np.mean(scores[:mid]) if scores[:mid] else 50.0
                    avg2 = np.mean(scores[mid:]) if scores[mid:] else 50.0
                    if avg2 > avg1 + 5: current_analysis_api['trend'] = 'Improving'
                    elif avg2 < avg1 - 5: current_analysis_api['trend'] = 'Declining'
            last_score = scores[-1] if scores else 50.0
            if last_score > 60: current_analysis_api['overall_sentiment'] = 'Positive'
            elif last_score < 40: current_analysis_api['overall_sentiment'] = 'Negative'

        current_analysis_api['source_distribution'] = {
            'reddit': round(avg_p_perc * 0.6 if avg_p_perc is not None else 0, 1),
            'telegram': round(avg_p_perc * 0.4 if avg_p_perc is not None else 0, 1)
        }
        if avg_p_perc < 5:
             current_analysis_api['source_distribution']['reddit'] = 30.0
             current_analysis_api['source_distribution']['telegram'] = 20.0


        final_result = {'timeline_data': output_timeline_list_api, 'analysis': current_analysis_api, 'period_days': days}
        cleaned_final_result = replace_nan_with_none(final_result)
        return jsonify(cleaned_final_result)
    except Exception as e: print(f"Error in /api/sentiment-timeline: {e}"); traceback.print_exc(); return jsonify(replace_nan_with_none({"error": "Sentiment timeline error", "details": str(e)})), 500

if __name__ == "__main__":
    print("Starting Flask server & scheduler...")
    with app.app_context():
        print("Attempting DB table check/creation...");
        try: db.create_all(); print("DB tables check/creation complete.")
        except Exception as e: print(f"Error during db.create_all(): {e}");
        print("Ensure migrations if schema changed.")

    scheduler = BackgroundScheduler(daemon=True, timezone='Asia/Amman')
    scheduler.add_job(func=lambda: asyncio.run(update_features_and_predictions_job()), trigger='cron', hour=3, minute=0, id='daily_update_job', replace_existing=True)
    run_time_initial = datetime.now(pytz_timezone('Asia/Amman')) + timedelta(seconds=15)
    print(f"Scheduling one-time update: {run_time_initial.strftime('%Y-%m-%d %H:%M:%S %Z%z')}")
    scheduler.add_job(func=lambda: asyncio.run(update_features_and_predictions_job()), trigger='date', run_date=run_time_initial, id='initial_populate_job', replace_existing=True)

    with app.app_context():
        try:
            is_empty = not DailyFeatures.query.first() and not TelegramMessage.query.first() and not RedditMessage.query.first() and not ModelPredictions.query.first()
            if is_empty: print("DB appears empty. Initial job scheduled.")
            else: print("DB has data. Scheduled jobs will update.")
        except Exception as e: print(f"Error checking DB emptiness: {e}")

    scheduler.start(); print(f" Scheduler started. Daily job at 3:00 AM ({scheduler.timezone}). Initial run in ~15s.")
    atexit.register(lambda: scheduler.shutdown(wait=False))
    print("Flask server starting on http://127.0.0.1:5000 ...")
    app.run(debug=True, port=5000, use_reloader=False)